tmux:
    symbols:
        branch: " "
        hashprefix: ":"
        ahead: "↑"
        behind: "↓"
        staged: " "
        conflict: " "
        modified: " "
        untracked: " "
        stashed: " "
        insertions: ""
        deletions: ""
        clean: " "

    # Catppuccin Mocha colors
    styles:
        clear: "#[none]"
        state: "#[fg=#f38ba8,bold]"
        branch: "#[fg=#cba6f7,bold]"
        remote: "#[fg=#89b4fa]"
        divergence: "#[fg=#f9e2af]"
        staged: "#[fg=#a6e3a1,bold]"
        conflict: "#[fg=#f38ba8,bold]"
        modified: "#[fg=#fab387,bold]"
        untracked: "#[fg=#94e2d5]"
        stashed: "#[fg=#89b4fa]"
        insertions: "#[fg=#a6e3a1]"
        deletions: "#[fg=#f38ba8]"
        clean: "#[fg=#a6e3a1,bold]"

    layout: [branch, divergence, " ", flags]

    options:
        branch_max_len: 20
        branch_trim: right
        ellipsis: …
        hide_clean: false
        swap_divergence: false
        divergence_space: false
        flags_without_count: false
