[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # lsp
repo = 'prabirshrestha/vim-lsp'

[[plugins]] # lsp-settings
repo = 'mattn/vim-lsp-settings'
merged = 0

[[plugins]] # auto-completion
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]] # auto-completion
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]] # スニペット補完
repo = 'Shougo/neosnippet.vim'

[[plugins]] # スニペット集
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # Ruby endwise補完
repo = 'tpope/vim-endwise'

[[plugins]] # ファイル名補完 ctrl p
repo = "ctrlpvim/ctrlp.vim"

[[plugins]] # 英単語補完
repo = 'ujihisa/neco-look'

[[plugins]] # Rails
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]] # ディレクトリツリー表示
repo = 'scrooloose/nerdtree'

#[[plugins]] # ファイルアイコン
#repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

#[[plugins]] # ファイルアイコン
#repo = 'ryanoasis/vim-devicons'

[[plugins]] # スペース可視化
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # Git
repo = 'tpope/vim-fugitive'

[[plugins]] # Gitステータス表示
repo = 'airblade/vim-gitgutter'

[[plugins]] # Vimステータスライン表示
repo = 'itchyny/lightline.vim'

[[plugins]] # tag アウトライン
repo = 'majutsushi/tagbar'

[[plugins]] # ctag
repo = 'szw/vim-tags'

[[plugins]] # javascript
repo = 'pangloss/vim-javascript'

[[plugins]] # React(jsx)
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]] # typescript
repo = 'leafgarland/typescript-vim'

[[plugins]] # scala
repo = 'derekwyatt/vim-scala'

[[plugins]] # Haskell
repo = 'neovimhaskell/haskell-vim'

[[plugins]] # cheatsheet
repo = 'reireias/vim-cheatsheet'

[[plugins]] # sub window resize
repo = 'simeji/winresizer'

[[plugins]] # HTML5
repo = 'othree/html5.vim'

[[plugins]] # CSS3
repo = 'hail2u/vim-css3-syntax'

[[plugins]] # Golang :Goimport, :w (with lint)
repo = 'mattn/vim-goimports'

